require "my.autocmds"
require "my.options"
require "my.commands"
require "my.mappings"

require "my.plugins"
require "my.plugins.toggleterm"
require "my.plugins.treesitter"
require "my.plugins.telescope"
require "my.plugins.telescope_fzf_native"
require "my.plugins.vim_oldfiles"
require "my.plugins.dressing"
require "my.plugins.null_ls"
require "my.plugins.fix_cursor_hold"

require "my.lsp.erlangls"
require "my.lsp.sumneko_lua"
require "my.lsp.pyright"

require "my.lsp.markdownlint"
require "my.lsp.plantuml"
require "my.lsp.prettier"
require "my.lsp.stylua"
-- require "my.lsp.vale"
