require "my.autocmds"
require "my.options"
require "my.commands"
require "my.mappings"

require "my.plugins.packer"

require "my.plugins.base16"
require "my.plugins.builtin_plugins"
require "my.plugins.commentary"
require "my.plugins.dressing"
require "my.plugins.erlang_syntax_simple"
require "my.plugins.fix_cursor_hold"
require "my.plugins.folding"
require "my.plugins.heirline"
require "my.plugins.lists"
require "my.plugins.lspconfig"
require "my.plugins.markdown_preview"
require "my.plugins.microscope"
require "my.plugins.null_ls"
require "my.plugins.plantuml_syntax"
require "my.plugins.plenary"
require "my.plugins.repeat"
require "my.plugins.surround"
require "my.plugins.telescope"
require "my.plugins.telescope_fzf_native"
require "my.plugins.toggleterm"
require "my.plugins.treesitter"
require "my.plugins.vader"
require "my.plugins.vim_oldfiles"
require "my.plugins.which_key"

require "my.lsp.erlangls"
require "my.lsp.sumneko_lua"
require "my.lsp.pyright"

require "my.lsp.markdownlint"
require "my.lsp.plantuml"
require "my.lsp.prettier"
require "my.lsp.stylua"
-- require "my.lsp.vale"
