" General settings{{{
if has('nvim')
    set runtimepath^=~/.vim runtimepath+=~/.vim/after
    let &packpath = &runtimepath
    set completeopt=menu,menuone " Display insertion completion as a popup
    set fillchars=eob:\     " Remove the tilde at lines at end of buffer
else
    set nocompatible " Use Vim settings rather than Vi settings
    set backspace+=indent,eol,start " Allow backspace in insert mode
    set incsearch " Find the next search as we type search
    set encoding=utf-8 " Text encoding
    set ruler
    set laststatus=2
    syntax enable
    set wildmenu
    set completeopt=menuone,popup " Display insertion completion as a popup
    if exists("$COLORTERM")
        " Fancy colors
        " According to :h xterm-true-color
        " t_8f and t_8b are only set when $TERM is xterm*
        " In tmux, $TERM is screen by default.
        " Therefore, we have to set them explicitly here.
        let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
        let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
        " Change cursor shape depending on mode
        let &t_SI = "\e[5 q"
        let &t_EI = "\e[2 q"
    endif
endif

set langmenu=none " Disable localized menus
filetype plugin indent on
set smartindent " Takes the indent of above line, useful for regular txt-files
set expandtab " Expands tab into spaces
set shiftwidth=4 " Width when using <, >
set shiftround " When using <, >, round to nearest shiftwidth
set softtabstop=4 " Actual length when using tabs
set ignorecase " Ignore case when searching...
set smartcase " ...unless we type a capital
if has('clipboard')
    set clipboard=unnamed " Yank/paste automatically to/from system clipboard
endif
set foldlevel=99 " Start with all folds open
set ttimeoutlen=0 " Delay after pressing ESC and another character
set path=.,, " Search relative to current dir and in current dir
set path+=/Users/arvidbjurklint/Dropbox/Chalmers/
set path+=/Users/arvidbjurklint/Dropbox/dotfiles/
set wildignore=*.aux,*.log,*.fdb_latexmk,*.fls,*.out,*.synctex.gz,
set wildignorecase
set nohlsearch
set breakindent " Indents word-wrapped lines as much as the parent line
set textwidth=80 " Sets when the line should break
set linebreak " Ensures word-wrap does not split words 
set splitbelow splitright " Open new windows below the current and to the right
set shortmess=I " Disables intro on startup
set number " Show line number on the left
set relativenumber " Show numbers relative to current line number
set scrolloff=2 " Minimal number of lines to keep above and below the cursor
"}}}

" Plugins {{{

" Ensure vim-plug is installed
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

call plug#begin('~/.vim/plugged')
    Plug 'morhetz/gruvbox'
    Plug 'tpope/vim-commentary'
    Plug 'neomake/neomake'
    Plug 'slarwise/vim-tmux-cycle'
    Plug 'slarwise/vim-lifeline'
    Plug 'slarwise/vim-tmux-send'
call plug#end()

" gruvbox
let g:gruvbox_contrast_light='soft'
let g:gruvbox_contrast_dark='soft'
let g:gruvbox_italic=1
let g:gruvbox_italicize_comments=1
let g:gruvbox_invert_selection=0

" tex
let g:tex_no_error=1
let g:tex_flavor='latex'
let g:tex_noindent_env = 'document\|verbatim\|lstlisting\|center'
let g:tex_fold_enabled = 1

" neomake
augroup compile_on_write
    autocmd!
    autocmd BufWritePost *.mkiv,*.md
                \ :if exists("b:compile_on_write") && b:compile_on_write | 
                \ Neomake! |
                \ endif
augroup END
"}}}

" Display{{{
set background=light

if exists("$COLORTERM")
    set termguicolors
    colorscheme gruvbox
else
    colorscheme zellner
endif
"}}}

" Mappings{{{
let mapleader=" "
let maplocalleader="-"

nnoremap <LEADER>w :w<CR>
nnoremap <LEADER>q :q<CR>
nnoremap <LEADER>Q :qall<CR>
noremap ö :
nnoremap qö q:

nnoremap <LEADER>th :set hlsearch!<CR>
nnoremap <LEADER>tb :let &bg = (&bg==#'dark' ? 'light' : 'dark') <CR>
let g:is_zen = 0
function! Zen()
    if g:is_zen
        set number relativenumber laststatus=2 ruler
        let g:is_zen = 0
    else
        set nonumber norelativenumber laststatus=0 noruler
        let g:is_zen = 1
    endif
endfunction
nnoremap <LEADER>tz :call Zen() <CR>

nnoremap <LEADER>m :Neomake <CR>
nnoremap <LEADER>M :Neomake! <CR>
nnoremap <LEADER>co :copen<BAR>wincmd p <CR>
nnoremap <LEADER>cc :cclose <CR>
nnoremap <LEADER>cn :cnext <CR>
nnoremap <LEADER>cn :cprev <CR>

nnoremap <LEADER>sm :source ~/.vim/vimrc <CR>
nnoremap <LEADER>em :edit ~/.vim/vimrc <CR>

nnoremap <LEADER>ef :e ~/Dropbox/dotfiles/.vim/after/ftplugin/
nnoremap <LEADER>et :sp ~/Dropbox/Chalmers/todo.md<CR>

nnoremap <LEADER>f :find **/

nnoremap <silent> <c-j> :VimTmuxCycleNext <CR>
nnoremap <silent> <c-k> :VimTmuxCyclePrevious <CR>

nnoremap <LEADER>pm :SendMakeCmd <CR>
nnoremap <LEADER>pp :SendLine <CR>
nnoremap <silent> <LEADER>p :set operatorfunc=SendSelection<CR>g@
nnoremap <LEADER>pe :SendKeys "ENTER" <CR>
nnoremap <LEADER>pl :SendKeys "C-l" <CR>
nnoremap <LEADER>pu :SendKeys "C-u" <CR>
"}}}

" vim:set foldmethod=marker foldlevel=0:
