require "my.autocmds"
require "my.options"
require "my.commands"
require "my.mappings"

require "my.plugins"
require "my.setups.toggleterm"
require "my.setups.treesitter"
require "my.setups.telescope"
require "my.setups.telescope_fzf_native"
require "my.setups.vim_oldfiles"
require "my.setups.dressing"

require "my.lsp"
require "my.lsp.lspconfig"
require "my.lsp.null_ls"
