#!/bin/sh

# Reads system background and updates alacritty, nvim and tmux colors
# accordingly. Checks if background mode has changed on every full minute.

# Check if this script is already running
n_ps_matches=$(ps | grep 'monitor-background-mode' | wc -l)
if [ $n_ps_matches -gt 3 ]; then
    exit 1
fi

mode=$(get-background-mode)
set-background all $mode

while true; do
    new_mode=$(get-background-mode)
    if [ $new_mode != $mode ]; then
        mode=$new_mode
        set-background all $mode
    fi
    sleep $((60 - $(date +%S) ))
done
