#!/bin/sh
# Symlink all dotfiles to the home directory

set -e

files=(.bin .gitconfig .tmux.conf .vim .zshrc)

for file in "${files[@]}"
do
    ln -s ~/Dropbox/dotfiles/"$file" ~/"$file"
done

# vim: set filetype=sh:
