#!/bin/sh
# Sends C-j/k if Vim is running in the current pane and goes to the top/bottom
# of the vim windows if we enter with j/k
# Need to fix such that going from a pane with vim to another pane with vim
# works correctly

set -e

cmd="$(tmux display -p '#{pane_current_command}')"

if [ $cmd = "vim" ]; then
    direction="$(echo "$@" | tr '+-' 'jk')"
    tmux send-keys "C-$direction"
else
    tmux select-pane -t "$@"
    cmd_new_pane="$(tmux display -p '#{pane_current_command}')"
    if [ $cmd_new_pane = "vim" ]; then
        if [ "$@" = + ]; then
            tmux send-keys C-w t
        else
            tmux send-keys C-w b
        fi
    fi
fi
