#!/bin/bash

set -e

mode="$(get-background-mode)"

if [ $mode = "dark" ]; then
    tmux set-option -g status-style 'bg=#504945 fg=#ebdbb2'
    tmux set-option -g clock-mode-colour '#ebdbb2'
    tmux set-option -g pane-border-style 'fg=#504945'
    tmux set-option -g pane-active-border-style 'fg=#ebdbb2'
else
    tmux set-option -g status-style 'bg=#d5c4a1 fg=#3c3836'
    tmux set-option -g clock-mode-colour '#3c3836'
fi
