# Zsh settings
autoload -Uz compinit # Initialize auto completion
compinit
setopt menucomplete # Go to first completion match straight away
setopt autocd # Don't have to write cd before dir
setopt globstarshort # Writing ** means **/*

# Zsh syntax highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Completion for kitty functions
kitty + complete setup zsh | source /dev/stdin

# Vi keybindings in zsh
bindkey -v

# Set stand-alone context earlier than texlive version in PATH. Screws up
# matplotlib.
# export PATH=/Users/arvidbjurklint/context/tex/texmf-osx-64/bin:$PATH

# Python path
export PATH=/usr/local/opt/python/libexec/bin:$PATH

# Add path to my scripts
export PATH=$PATH:~/.bin

# Language settings
export LANG="sv_SE.UTF-8"
export LC_ALL="sv_SE.UTF-8"

# Aliases
alias cdd="cd ~/Dropbox/dotfiles/"
alias cdc="cd ~/Dropbox/Chalmers/"
alias cde="cd ~/Dropbox/Chalmers/exjobb"
alias context-commands="open ~/Dropbox/Chalmers/report-writing/context/docs/setup-en.pdf"
alias context-ref="open ~/Dropbox/Chalmers/report-writing/context/docs/contextref.pdf"
alias pv="qlmanage -p"
alias icat="kitty +kitten icat"
alias termpdf="~/termpdf/termpdf.py"
alias unimatrix="~/unimatrix/unimatrix.py"

# Environment variables to directories
export DOTS=/Users/arvidbjurklint/Dropbox/dotfiles
export CHALMERS=/Users/arvidbjurklint/Dropbox/Chalmers
