# Zsh settings
autoload -Uz compinit # Initialize auto completion
compinit
setopt autocd # Don't have to write cd before dir
setopt globstarshort # Writing ** means **/*

# Zsh syntax highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Completion for kitty functions
kitty + complete setup zsh | source /dev/stdin

# Vi keybindings in zsh
bindkey -v

# Python path
export PATH=/usr/local/opt/python/libexec/bin:$PATH

# Add path to my scripts
export PATH=$PATH:~/.bin

# Language settings
export LANG="sv_SE.UTF-8"
export LC_ALL="sv_SE.UTF-8"

# Color output of commands, used by e.g. ls
export CLICOLOR=1

# Set my editor to neovim
export EDITOR=nvim

# Aliases
alias pv="qlmanage -p"
alias icat="kitty +kitten icat"

# Environment variables to directories
export DOTS=/Users/arvidbjurklint/Dropbox/dotfiles
