# Completion
autoload -Uz compinit
compinit
setopt menucomplete # Go to first match straight away

# Completion for kitty
kitty + complete setup zsh | source /dev/stdin

# Vi mode in terminal
bindkey -v

# Set stand-alone context earlier than texlive version in PATH. Screws up
# matplotlib.
# export PATH=/Users/arvidbjurklint/context/tex/texmf-osx-64/bin:$PATH

# Python path
export PATH=/usr/local/opt/python/libexec/bin:$PATH

# My own scripts
export PATH=$PATH:~/.bin

export LANG="sv_SE.UTF-8"
export LC_ALL="sv_SE.UTF-8"

setopt autocd # Don't have to write cd before dir
setopt globstarshort # Writing ** means **/*

alias cdd="cd ~/Dropbox/dotfiles/"
alias cdc="cd ~/Dropbox/Chalmers/"
alias cde="cd ~/Dropbox/Chalmers/exjobb"
alias context-commands="open ~/Dropbox/Chalmers/report-writing/context/docs/setup-en.pdf"
alias context-ref="open ~/Dropbox/Chalmers/report-writing/context/docs/contextref.pdf"
alias pv="qlmanage -p"
alias icat="kitty +kitten icat"
alias termpdf="~/termpdf/termpdf.py"
alias unimatrix="~/unimatrix/unimatrix.py"

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Start tmux when alacritty is started
# if [ "$TMUX" = "" ] && [ "$TERM_PROGRAM" = "alacritty" ]; then
#     tmux new-session -s slarwise
# fi

# Start tmux when kitty is started
# if [ "$TMUX" = "" ] && [ "$TERM_PROGRAM" = "kitty" ]; then
#     tmux new-session -s slarwise
# fi

# Set the title to the command just before it is run
# preexec() {
#    print -Pn "\e]0;$1\a"
# }

# Set the title to zsh after the command is done
# precmd() {
#     print -Pn "\e]0;zsh\a"
# }
